# Generated by Django 4.2.6 on 2023-12-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD'),
        ),
    ]
