# Generated by Django 4.2.6 on 2023-12-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patientId',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
